module.exports = {
    UNHANDLED_HANDLER_ERROR: 'UNHANDLED_HANDLER_ERROR',
    LOGGER_STREAM_FLUSH_ERROR: 'LOGGER_STREAM_FLUSH_ERROR',
    DB_CREDENTIALS_RESTORE_ERROR: 'DB_CREDENTIALS_RESTORE_ERROR',
    UNABLE_TO_CONNECT_DATABASE: 'UNABLE_TO_CONNECT_DATABASE',
    DATABASE_CONNECTED: 'DATABASE_CONNECTED'
};
